const PENDING_REQUEST = 'PENDING_REQUEST';
const SUCCESS_REQUEST = 'SUCCESS_REQUEST';
const FAILURE_REQUEST = 'FAILURE_REQUEST';
const ADD_TASK = 'ADD_TASK';
const REMOVE_TASK = 'REMOVE_TASK';
export { PENDING_REQUEST, SUCCESS_REQUEST, FAILURE_REQUEST, ADD_TASK, REMOVE_TASK }